name: spatialtk
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.9
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - pip:
      - --extra-index-url https://miropsota.github.io/torch_packages_builder 
      - --extra-index-url https://pypi.nvidia.com
      - sphinx_rtd_theme==1.2.0
      - sphinx-hoverxref==1.3.0
      - anndata==0.8.0
      - scanpy==1.8.1
      - numpy==1.20.3
      - pandas==1.4.2
      - matplotlib==3.5.2
      - seaborn==0.11.2
      - scikit-learn==0.24.1 
      - einops==0.4.1 
      - biopython==1.79
      - plotly==5.10.0
      - pytorch3d==0.7.6+pt2.2.1cu121
      - torch==2.2.1+cu121
      - scipy==1.10.0
      - pyimzml==1.5.3
      - intervaltree
      - shapely==2.0.3
      - svgpathtools==1.6.1